[package]
name = "day08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_shared = { workspace = true }
nom = "7.1.3"
num-integer = "0.1.45"
