name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.AOC_INPUTS_2023 }}
    - uses: actions/checkout@v3
    - name: Fetch inputs
      run: git submodule init && git submodule update --remote
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build all for release
      run: cargo build --release
    - name: Run all
      run: |
        cargo run --release --bin day01
        cargo run --release --bin day02
        cargo run --release --bin day03
        cargo run --release --bin day04
        cargo run --release --bin day07
